baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Joshua Concon's Blog"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blogposts"
    url = "/blogposts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "I am Joshua Concon and this is where my blog posts live. I write about Software Engineering and everything adjacent to it."

